services:
  geotagger_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - geotagger_network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: geotagger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - geotagger_network

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    networks:
      - geotagger_network

  test_redis:
    image: redis:7
    ports:
      - "6380:6379"
    networks:
      - geotagger_network

  test_db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: geotagger_test
    ports:
      - "5433:5432"
    networks:
      - geotagger_network

volumes:
  postgres_data:
  redis_data:

networks:
  geotagger_network:
    driver: bridge
