export enum AuthErrorCode {
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNSUPPORTED_AUTH_PROVIDER = 'UNSUPPORTED_AUTH_PROVIDER',
  CANNOT_CHANGE_PASSWORD = 'CANNOT_CHANGE_PASSWORD',
}
